### ISSUE TITLE
SM-DP parse 'change profile status response message' WRONG

### ISSUE THREAD

**Issue by liuhu** [bagyenda/njiwa#1]
https://github.com/bagyenda/njiwa/blob/54a2ba6600777fe40e29370ef93e78cb35e5ae03/src/io/njiwa/dp/transactions/ChangeProfileStatusTransaction.java#L99-L104

The byte response data is from soap param euiccResponseData which is eUICC RAPDU. So we can't  transform to `BaseResponseType.ExecutionStatus`.

Maybe we need to parse it like this :
https://github.com/bagyenda/njiwa/blob/54a2ba6600777fe40e29370ef93e78cb35e5ae03/src/io/njiwa/dp/transactions/DownloadProfileTransaction.java#L140-L150

**Comment by bagyenda** [comment]
Thanks for this. I am still not sure we need to look at the eUICC response data. If you look at Appendix A.6.9, the response from the SM-SR will indicate to the result to the SM-DP using the BaseResponseType (since the SM-SR processes this command via ES5 -- see io.njiwa.sr.ota.Ota.processMO). Only when there is an error will the eUICC response data be included. It seems to me it shouldn't matter.
